import numpy as np

r"""Toy 2D p+ip BdG model with two vortices and Berry holonomy of zero modes.

This script is a *very* simplified lattice realization of a spinless 2D
p+ip topological superconductor on a square lattice, with two vortices
inserted via a spatially varying superconducting phase. The goals are:

  1. Build a finite-size BdG Hamiltonian H(lambda) along a parameterized
      path lambda \\in [0, 1] where one vortex moves adiabatically around
     the other on the lattice.
  2. At each lambda, extract the low-energy "zero-mode" subspace
     spanned by the eigenvectors with the smallest |E|.
  3. Using parallel transport based on overlaps between neighboring
     eigenbases, compute the non-Abelian Berry holonomy U_Berry around
     the closed loop in vortex configuration space.

The resulting U_Berry acts on the (approximately) degenerate ground-state
subspace generated by the Majorana zero modes bound to the vortices. In
principle, for well-separated vortices and in the topological phase,
this holonomy should reproduce the Ising anyon braid / Dehn twist matrix
up to a basis change and overall phase.

This is only a starting point / scaffold and makes many simplifying
assumptions. It is intended to mirror, in spirit, the 4-Majorana toy
scripts used earlier for 1D, but now in a 2D lattice p+ip setting.
"""


def lattice_indices(Lx: int, Ly: int):
    """Return a dict mapping (x, y) -> site index and its inverse.

    x in {0,...,Lx-1}, y in {0,...,Ly-1}. We use open boundary conditions
    (no wrapping) to keep the geometry simple.
    """
    idx_of = {}
    pos_of = {}
    idx = 0
    for y in range(Ly):
        for x in range(Lx):
            idx_of[(x, y)] = idx
            pos_of[idx] = (x, y)
            idx += 1
    return idx_of, pos_of


def superconducting_phase_at(x: float, y: float, vortices):
    """Compute a simple continuum-inspired superconducting phase theta(x,y).

    vortices: list of (x_v, y_v) positions (can be floats) representing
    vortex cores. We approximate the phase as a sum of polar angles
    around each vortex:

        theta(x, y) = sum_v arg((x - x_v) + i (y - y_v)).

    This is crude (no branch cut handling / self-consistent solution),
    but adequate for a toy model of the pairing phase texture.
    """
    theta = 0.0
    for (xv, yv) in vortices:
        dx = x - xv
        dy = y - yv
        theta += np.arctan2(dy, dx)
    return theta


def build_pip_bdg(Lx: int, Ly: int, mu: float, t: float, delta0: float, vortices):
    """Build a BdG Hamiltonian for a spinless 2D p+ip superconductor.

    Basis: N sites, with N=Lx*Ly. We use Nambu basis (c, c^\\dagger):

        Psi = (c_0,...,c_{N-1}, c_0^\dagger,...,c_{N-1}^\dagger)^T

    Then BdG Hamiltonian has block form

        H = [[h,    Delta],
             [Delta^\dagger, -h^T]],

    where h is the normal hopping part and Delta encodes p+ip pairing
    on nearest-neighbor bonds with a spatially varying phase coming from
    the vortices.
    """
    idx_of, pos_of = lattice_indices(Lx, Ly)
    N = Lx * Ly

    h = np.zeros((N, N), dtype=complex)
    Delta = np.zeros((N, N), dtype=complex)

    # On-site chemical potential term
    for i in range(N):
        h[i, i] = -mu

    # Nearest-neighbor hopping and p+ip pairing
    # We take t real and pairing amplitudes
    #   Delta_x =  delta0 (p_x)
    #   Delta_y =  i delta0 (p_y)
    # with an additional spatial phase factor from the vortex texture.
    for i in range(N):
        x, y = pos_of[i]

        # right neighbor (x+1, y)
        if x + 1 < Lx:
            j = idx_of[(x + 1, y)]
            # normal hopping
            h[i, j] = -t
            h[j, i] = -t

            # pairing on bond i->j
            theta_i = superconducting_phase_at(x, y, vortices)
            theta_j = superconducting_phase_at(x + 1, y, vortices)
            phase_ij = np.exp(0.5j * (theta_i + theta_j))
            # p_x component: real Delta_x
            Delta_ij = delta0 * phase_ij
            # antisymmetry: Delta_{ji} = -Delta_{ij}
            Delta[i, j] += Delta_ij
            Delta[j, i] -= Delta_ij

        # up neighbor (x, y+1)
        if y + 1 < Ly:
            j = idx_of[(x, y + 1)]
            # normal hopping
            h[i, j] = -t
            h[j, i] = -t

            theta_i = superconducting_phase_at(x, y, vortices)
            theta_j = superconducting_phase_at(x, y + 1, vortices)
            phase_ij = np.exp(0.5j * (theta_i + theta_j))
            # p_y component: i delta0
            Delta_ij = 1j * delta0 * phase_ij
            Delta[i, j] += Delta_ij
            Delta[j, i] -= Delta_ij

    # Assemble full BdG Hamiltonian
    H = np.zeros((2 * N, 2 * N), dtype=complex)
    H[0:N, 0:N] = h
    H[0:N, N:2 * N] = Delta
    H[N:2 * N, 0:N] = Delta.conj().T
    H[N:2 * N, N:2 * N] = -h.T

    return H


def low_energy_subspace(H: np.ndarray, dim_sub: int = 2):
    """Return eigenvalues and eigenvectors of the lowest-|E| states.

    We diagonalize H (Hermitian) and sort by |E| ascending, then return
    the first dim_sub eigenvalues and eigenvectors as columns of a
    (dim(H) x dim_sub) matrix.
    """
    w, v = np.linalg.eigh(H)
    idx = np.argsort(np.abs(w))
    sel = idx[:dim_sub]
    w_sel = w[sel]
    V_sel = v[:, sel]
    return w_sel, V_sel


def print_low_spectrum(H: np.ndarray, num: int = 8) -> None:
    """Utility: print the lowest-|E| eigenvalues to inspect the gap/zero modes."""
    w, _ = np.linalg.eigh(H)
    idx = np.argsort(np.abs(w))
    sel = idx[:num]
    print("Lowest-|E| eigenvalues:")
    print(np.round(w[sel], 6))


def project_to_unitary(W: np.ndarray) -> np.ndarray:
    """Project overlap matrix W to the closest unitary via polar decomposition.

    W = U S V^\\dagger -> U_polar = U V^\\dagger.
    """
    U, s, Vh = np.linalg.svd(W)
    return U @ Vh


def normalize_to_su2(U: np.ndarray) -> np.ndarray:
    """Strip global phase so that det(U) = 1, giving an SU(2) representative.

    For a 2x2 unitary U, we divide by sqrt(det U). Either branch of the
    square root differs only by an overall phase, which is irrelevant for
    gate equivalence in TQFT.
    """
    det = np.linalg.det(U)
    sqrt_det = np.sqrt(det)
    return U / sqrt_det


def ising_R_and_dehn_su2() -> tuple[np.ndarray, np.ndarray]:
    """Return SU(2)-normalized Ising R^{σσ} and its square (Dehn twist).

    We use the standard Ising R-symbols

        R^{σσ}_1  = exp(-iπ/8),
        R^{σσ}_ψ  = exp(3iπ/8).

    Then (R^{σσ})^2 has eigenvalues exp(-iπ/4), exp(3iπ/4). After stripping
    the overall phase, both R and R^2 can be viewed as SU(2) elements.
    """
    R1 = np.exp(-0.125j * np.pi)
    Rpsi = np.exp(0.375j * np.pi)
    R = np.diag([R1, Rpsi])
    R2 = np.diag([R1**2, Rpsi**2])

    R_su2 = normalize_to_su2(R)
    R2_su2 = normalize_to_su2(R2)
    return R_su2, R2_su2


def su2_fidelity(U_target: np.ndarray, U_candidate: np.ndarray) -> tuple[float, complex]:
    """Phase-agnostic overlap F = |Tr(U_target^† U_candidate)| / 2.

    For 2x2 unitaries in SU(2), F=1 means they differ only by a global phase.
    """
    M = U_target.conj().T @ U_candidate
    tr = np.trace(M)
    F = np.abs(tr) / 2.0
    return F, tr


def vortex_loop_path(Lx: int, Ly: int, n_steps_segment: int = 10):
    """Define a simple rectangular loop where vortex 2 moves around vortex 1.

    For simplicity, we fix vortex 1 at the center of the lattice and move
    vortex 2 along a discrete rectangular path encircling it. We return
    a list of (v1_pos, v2_pos) pairs, where each position is a (x, y)
    tuple in lattice coordinates (floats are allowed for smoother motion
    if desired).
    """
    cx = (Lx - 1) / 2.0
    cy = (Ly - 1) / 2.0
    v1 = (cx, cy)

    # Define a rectangle around the center in continuous coordinates
    R = min(Lx, Ly) / 4.0
    x_min = cx - R
    x_max = cx + R
    y_min = cy - R
    y_max = cy + R

    path = []

    # Bottom edge: (x_min -> x_max, y_min)
    for k in range(n_steps_segment):
        t = k / n_steps_segment
        x = x_min + (x_max - x_min) * t
        y = y_min
        path.append((v1, (x, y)))

    # Right edge: (x_max, y_min -> y_max)
    for k in range(n_steps_segment):
        t = k / n_steps_segment
        x = x_max
        y = y_min + (y_max - y_min) * t
        path.append((v1, (x, y)))

    # Top edge: (x_max -> x_min, y_max)
    for k in range(n_steps_segment):
        t = k / n_steps_segment
        x = x_max - (x_max - x_min) * t
        y = y_max
        path.append((v1, (x, y)))

    # Left edge: (x_min, y_max -> y_min)
    for k in range(n_steps_segment):
        t = k / n_steps_segment
        x = x_min
        y = y_max - (y_max - y_min) * t
        path.append((v1, (x, y)))

    # Close the loop by repeating the first point
    path.append(path[0])
    return path


def compute_zero_mode_holonomy(Lx: int = 10, Ly: int = 10,
                               mu: float = 1.0, t: float = 1.0,
                               delta0: float = 1.0,
                               dim_sub: int = 2,
                               n_steps_segment: int = 8):
    """Compute Berry holonomy for the zero-mode subspace along a vortex loop.

    We discretize a rectangular loop where vortex 2 moves around vortex 1,
    build H for each point, extract the lowest-|E| subspace, and parallel
    transport it around the loop using overlap matrices projected to the
    nearest unitary.
    """
    path = vortex_loop_path(Lx, Ly, n_steps_segment=n_steps_segment)

    # Initial point
    v1_0, v2_0 = path[0]
    vortices_0 = [v1_0, v2_0]
    H0 = build_pip_bdg(Lx, Ly, mu, t, delta0, vortices_0)
    _, V_prev = low_energy_subspace(H0, dim_sub=dim_sub)

    U_holo = np.eye(dim_sub, dtype=complex)

    for k in range(len(path) - 1):
        v1_k, v2_k = path[k + 1]
        vortices_k = [v1_k, v2_k]
        Hk = build_pip_bdg(Lx, Ly, mu, t, delta0, vortices_k)
        _, V_next = low_energy_subspace(Hk, dim_sub=dim_sub)

        W = V_prev.conj().T @ V_next  # dim_sub x dim_sub
        U_step = project_to_unitary(W)
        U_holo = U_step @ U_holo

        V_prev = V_next

    return U_holo


def main():
    # Use a somewhat larger lattice and parameters deep in the
    # topological regime (heuristically: mu inside the band, pairing
    # not too large).
    Lx, Ly = 20, 20
    mu = -2.0
    t = 1.0
    delta0 = 0.5
    dim_sub = 2
    # More steps along the loop improve the Berry holonomy discretization.
    n_steps_segment = 12

    # Inspect the low-energy spectrum at the initial vortex configuration
    # to check that we indeed have near-zero modes separated by a gap.
    from copy import deepcopy
    path0 = vortex_loop_path(Lx, Ly, n_steps_segment=n_steps_segment)
    v1_0, v2_0 = path0[0]
    H0 = build_pip_bdg(Lx, Ly, mu, t, delta0, [v1_0, v2_0])
    print("=== Initial spectrum diagnostics ===")
    print_low_spectrum(H0, num=8)

    U_holo = compute_zero_mode_holonomy(Lx=Lx, Ly=Ly,
                                        mu=mu, t=t, delta0=delta0,
                                        dim_sub=dim_sub,
                                        n_steps_segment=n_steps_segment)
    evals, _ = np.linalg.eig(U_holo)

    print("=== 2D p+ip vortex loop Berry holonomy ===")
    print("U_holo ({}x{}) =".format(dim_sub, dim_sub))
    print(np.round(U_holo, 6))
    print("Eigenvalues of U_holo:")
    print(np.round(np.sort_complex(evals), 6))

    # Normalize to SU(2) by stripping the global phase
    U_holo_su2 = normalize_to_su2(U_holo)
    evals_su2, _ = np.linalg.eig(U_holo_su2)
    print("\nU_holo normalized to SU(2) (det=1):")
    print(np.round(U_holo_su2, 6))
    print("Eigenvalues of U_holo_su2:")
    print(np.round(np.sort_complex(evals_su2), 6))

    # Ising R^{σσ} and Dehn twist (R^{σσ})^2, both SU(2)-normalized
    R_ising_su2, Dehn_ising_su2 = ising_R_and_dehn_su2()
    evals_R, _ = np.linalg.eig(R_ising_su2)
    evals_Dehn, _ = np.linalg.eig(Dehn_ising_su2)

    print("\n=== Ising R^{σσ} (SU(2)-normalized) ===")
    print("R_ising_su2 =")
    print(np.round(R_ising_su2, 6))
    print("Eigenvalues of R_ising_su2:")
    print(np.round(np.sort_complex(evals_R), 6))

    print("\n=== Ising Dehn twist (R^{σσ})^2 (SU(2)-normalized) ===")
    print("Dehn_ising_su2 =")
    print(np.round(Dehn_ising_su2, 6))
    print("Eigenvalues of Dehn_ising_su2:")
    print(np.round(np.sort_complex(evals_Dehn), 6))

    # Phase-agnostic overlaps between U_holo_su2 and Ising R / Dehn twist
    F_R, tr_R = su2_fidelity(R_ising_su2, U_holo_su2)
    F_Dehn, tr_Dehn = su2_fidelity(Dehn_ising_su2, U_holo_su2)

    print("\n=== Phase-agnostic comparison (SU(2)) ===")
    print("Tr(R_ising_su2^† U_holo_su2) =", tr_R)
    print("F_R    = |Tr|/2 =", F_R)
    print("Tr(Dehn_ising_su2^† U_holo_su2) =", tr_Dehn)
    print("F_Dehn = |Tr|/2 =", F_Dehn)


if __name__ == "__main__":
    main()
