#!/usr/bin/env python3
"""Create GIFs (if possible) and an HTML gallery from `results/` PNGs.

Usage: python3 tools/make_gallery_and_gif.py
"""
import os, re
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
RESULTS = HERE / 'results'
os.makedirs(RESULTS, exist_ok=True)

def collect_images():
    imgs = {}
    pattern = re.compile(r'3d_F(minus|plus)_b_y_([0-9.+-]+)\.png')
    for p in sorted(RESULTS.iterdir()):
        m = pattern.match(p.name)
        if not m: 
            continue
        kind = m.group(1)
        by = float(m.group(2))
        imgs.setdefault(kind, []).append((by, p.name))
    for k in imgs:
        imgs[k].sort()
    return imgs

def try_make_gif(kind, frames, outpath):
    try:
        import imageio
    except Exception:
        return False, 'imageio not available'
    images = []
    for fn in frames:
        images.append(imageio.imread(str(RESULTS / fn)))
    imageio.mimsave(str(outpath), images, duration=0.8)
    return True, 'ok'

def make_html(imgs, gif_available):
    html = []
    html.append('<!doctype html>')
    html.append('<html><head><meta charset="utf-8"><title>F± 3D gallery</title>')
    html.append('<style>body{font-family:sans-serif;} .row{display:flex;align-items:center;margin:12px 0;} .col{margin-right:16px;} img{max-width:480px;border:1px solid #ccc;} .label{width:120px}</style>')
    html.append('</head><body>')
    html.append('<h2>Gallery: F_- (left) / F_+ (right) — b_y samples</h2>')

    kinds = [('minus','F_-'),('plus','F_+')]
    for kind,label in kinds:
        entries = imgs.get(kind, [])
        if not entries: continue
        html.append(f'<h3>{label} — {len(entries)} frames</h3>')
        # If gif exists, show it; otherwise show an animated JS viewer
        gif_name = f'anim_F{kind}.gif'
        gif_path = RESULTS / gif_name
        if gif_available.get(kind) and gif_path.exists():
            html.append(f'<div class="row"><div class="col"><img src="{gif_name}" alt="{label} gif"></div></div>')
        else:
            # JS slider
            frame_list = [e[1] for e in entries]
            varname = 'frames_' + kind
            html.append(f'<div class="row"><div class="col"><img id="{varname}_img" src="{frame_list[0]}" alt="{label}"></div>')
            html.append(f'<div class="col label"><button onclick="{varname}_prev()">Prev</button> <button onclick="{varname}_next()">Next</button></div></div>')
            html.append('<script>')
            html.append(f'var {varname} = {frame_list};')
            html.append(f'var idx_{varname} = 0;')
            html.append(f'function {varname}_next(){{ idx_{varname}=(idx_{varname}+1)%{len(frame_list)}; document.getElementById("{varname}_img").src={varname}[idx_{varname}]; }}')
            html.append(f'function {varname}_prev(){{ idx_{varname}=(idx_{varname}-1+{len(frame_list)})%{len(frame_list)}; document.getElementById("{varname}_img").src={varname}[idx_{varname}]; }}')
            html.append('</script>')

    html.append('<hr><p>Generated by tools/make_gallery_and_gif.py</p>')
    html.append('</body></html>')
    with open(RESULTS / 'gallery.html','w',encoding='utf8') as f:
        f.write('\n'.join(html))

def main():
    imgs = collect_images()
    if not imgs:
        print('No images found in results/. Run the plotting scripts first.')
        return
    gif_available = {}
    for kind, frames in imgs.items():
        frame_names = [fn for _,fn in frames]
        outgif = RESULTS / f'anim_F{kind}.gif'
        ok, msg = try_make_gif(kind, frame_names, outgif)
        gif_available[kind] = ok
        print(f'GIF for {kind}:', ok, msg)
    make_html(imgs, gif_available)
    print('Gallery written to', RESULTS / 'gallery.html')

if __name__ == '__main__':
    main()
