#!/usr/bin/env python3
"""Generate an HTML report summarizing deriveR outputs and figures.

Reads `results/deriveR_all_reports.pkl` (or individual `deriveR_report_delta*.pkl`),
embeds available PNGs from `results/`, and writes `results/deriveR_report.html`.
"""
import os
import glob
import pickle
import html
import datetime
import re


def load_all_reports(results_dir):
    p_all = os.path.join(results_dir, 'deriveR_all_reports.pkl')
    if os.path.exists(p_all):
        with open(p_all, 'rb') as f:
            return pickle.load(f)
    # fallback: collect individual report pickles
    reports = {}
    for p in sorted(glob.glob(os.path.join(results_dir, 'deriveR_report_delta*.pkl'))):
        with open(p, 'rb') as f:
            r = pickle.load(f)
        d = r.get('delta')
        if d is None:
            m = re.search(r'deriveR_report_delta([0-9eE+.-]+)\.pkl', os.path.basename(p))
            d = float(m.group(1)) if m else p
        reports[float(d)] = r
    return reports


def map_images_by_delta(results_dir):
    mapping = {}
    for p in glob.glob(os.path.join(results_dir, '*.png')):
        m = re.search(r'delta([0-9eE+_.-]+)', os.path.basename(p))
        if not m:
            continue
        sval = m.group(1).replace('_', '')
        try:
            d = float(sval)
        except Exception:
            continue
        mapping.setdefault(d, []).append(os.path.relpath(p))
    return mapping


def find_alpha_entry(report, alpha):
    # exact key
    key = f'alpha_{alpha:.6g}'
    if key in report:
        return key, report[key]
    # pick closest
    alpha_keys = [k for k in report.keys() if k.startswith('alpha_')]
    best = None
    best_diff = 1e9
    for k in alpha_keys:
        try:
            val = float(k.split('_', 1)[1])
        except Exception:
            continue
        d = abs(val - alpha)
        if d < best_diff:
            best_diff = d
            best = k
    return (best, report.get(best)) if best else (None, None)


def render_html(results_dir, all_reports, images_by_delta):
    now = datetime.datetime.utcnow().isoformat() + 'Z'
    html_lines = []
    html_lines.append('<!doctype html>')
    html_lines.append('<html><head><meta charset="utf-8"><title>deriveR Report</title>')
    html_lines.append('<style>body{font-family:Arial,Helvetica,sans-serif;margin:20px}h1,h2{color:#114}table{border-collapse:collapse}td,th{border:1px solid #ccc;padding:6px}</style>')
    html_lines.append('</head><body>')
    html_lines.append(f'<h1>deriveR Report</h1>')
    html_lines.append(f'<p>Generated: {html.escape(now)}</p>')

    deltas = sorted(all_reports.keys())
    html_lines.append('<h2>Summary table</h2>')
    html_lines.append('<table><tr><th>delta</th><th>I0</th><th>alpha_target</th><th>angle(alpha=1)</th><th>res_norm(alpha=1)</th><th>angle(alpha_target)</th><th>res_norm(alpha_target)</th></tr>')
    for d in deltas:
        r = all_reports[d]
        I0 = r.get('I0')
        at = r.get('alpha_target')
        k1, v1 = find_alpha_entry(r, 1.0)
        k2, v2 = find_alpha_entry(r, at) if at is not None else (None, None)
        angle1 = v1.get('angle') if v1 else ''
        rn1 = v1.get('res_norm') if v1 else ''
        angle2 = v2.get('angle') if v2 else ''
        rn2 = v2.get('res_norm') if v2 else ''
        html_lines.append(f'<tr><td>{d}</td><td>{I0:.6g}</td><td>{at:.6g}</td><td>{angle1}</td><td>{rn1}</td><td>{angle2}</td><td>{rn2}</td></tr>')
    html_lines.append('</table>')

    for d in deltas:
        html_lines.append(f'<h2>Delta = {d}</h2>')
        r = all_reports[d]
        html_lines.append('<ul>')
        html_lines.append(f'<li>I0: {r.get("I0")}</li>')
        html_lines.append(f'<li>alpha_target: {r.get("alpha_target")}</li>')
        html_lines.append('</ul>')
        imgs = images_by_delta.get(d, [])
        if imgs:
            html_lines.append('<div style="display:flex;flex-wrap:wrap;gap:12px">')
            for im in sorted(imgs):
                html_lines.append(f'<div style="width:360px"><img src="{im}" style="max-width:100%"><div style="font-size:0.9em">{os.path.basename(im)}</div></div>')
            html_lines.append('</div>')
        else:
            html_lines.append('<p><em>No PNGs found for this delta.</em></p>')

    html_lines.append('<hr/><p>Report generated by tools/generate_report_from_deriveR.py</p>')
    html_lines.append('</body></html>')
    return '\n'.join(html_lines)


def main():
    results_dir = os.path.join(os.getcwd(), 'results')
    if not os.path.isdir(results_dir):
        print('results/ directory not found. Run verify_from_R first.')
        return 2
    all_reports = load_all_reports(results_dir)
    if not all_reports:
        print('No reports found in results/.')
        return 3
    images_by_delta = map_images_by_delta(results_dir)
    html_text = render_html(results_dir, all_reports, images_by_delta)
    out = os.path.join(results_dir, 'deriveR_report.html')
    with open(out, 'w', encoding='utf-8') as f:
        f.write(html_text)
    print('Wrote HTML report to', out)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
